# Generated by Django 3.2 on 2023-05-21 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('periodic_type', models.TextField(choices=[('one', 'One'), ('batch', 'Batch')])),
                ('cost', models.IntegerField(verbose_name='Subscribe price')),
                ('charge_type', models.TextField(choices=[('daily', 'Daily'), ('one-time', 'One-Time')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscribe plan',
                'verbose_name_plural': 'Subscribe plans',
                'db_table': 'content"."subscribe',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('filmwork_id', models.ForeignKey(db_column='filmwork_id', on_delete=django.db.models.deletion.DO_NOTHING, to='movies.filmwork', verbose_name='Filmwork_id')),
                ('subscription_id', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, to='billing.subscription', verbose_name='Subscription_id')),
            ],
            options={
                'verbose_name': 'Subscription films',
                'verbose_name_plural': 'Subscription films',
                'db_table': 'content"."subscription_filmwork',
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionfilmwork',
            index=models.Index(fields=['subscription_id', 'filmwork_id'], name='subscription_filmwork_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['periodic_type'], name='subscription_periodic_type_idx'),
        ),
    ]
