# Generated by Django 3.2 on 2023-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_gw_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual Product ID on payment gateway'),
        ),
    ]
