# Generated by Django 3.2 on 2023-05-21 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(verbose_name='User id')),
                ('balance', models.IntegerField(verbose_name='User balance')),
                ('timestamp_offset', models.DateTimeField(verbose_name='Actual balance time')),
            ],
            options={
                'db_table': 'billing"."balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundsOnHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(editable=False, verbose_name='User id')),
                ('cost', models.IntegerField(verbose_name='Transaction amount')),
                ('timestamp', models.DateTimeField(verbose_name='Transaction complete date')),
                ('type', models.TextField(choices=[('spending', 'Spending'), ('refund', 'Refund')], verbose_name='Hold type')),
            ],
            options={
                'db_table': 'billing"."funds_hold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(editable=False, verbose_name='User id')),
                ('cost', models.IntegerField(verbose_name='Transaction amount')),
                ('timestamp', models.DateTimeField(verbose_name='Transaction complete date')),
                ('type', models.TextField(choices=[('topup', 'Top up'), ('spending', 'Spending'), ('refund', 'Refund')], verbose_name='Transaction type')),
            ],
            options={
                'db_table': 'billing"."transaction',
                'managed': False,
            },
        ),
    ]
