# Generated by Django 3.2 on 2023-05-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_balance_fundsonhold_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'managed': False, 'verbose_name': 'User balance', 'verbose_name_plural': 'Users balances'},
        ),
        migrations.AlterModelOptions(
            name='fundsonhold',
            options={'managed': False, 'verbose_name': 'Fund on hold (read-only)', 'verbose_name_plural': 'Funds on hold (read-only)'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False, 'verbose_name': 'Transaction (read-only)', 'verbose_name_plural': 'Transactions (read-only)'},
        ),
    ]
