# Generated by Django 3.2 on 2023-06-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20230529_1728'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscription_periodic_type_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='charge_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='periodic_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='all_time_cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='All time cost '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(blank=True, default=1, verbose_name='Duration of subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.IntegerField(verbose_name='Subscribe price per day'),
        ),
    ]
