# Generated by Django 3.2 on 2023-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20230601_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='all_time_cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='All time cost '),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(verbose_name='Duration of subscription'),
        ),
    ]
