# Generated by Django 4.2.1 on 2023-06-04 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20230601_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantedAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(db_column='uuid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(verbose_name='User id')),
                ('subscription_id', models.UUIDField(verbose_name='Subscription id')),
                ('granted_at', models.DateTimeField(verbose_name='Granted at')),
                ('available_until', models.DateTimeField(verbose_name='Grant available until')),
                ('is_active', models.BooleanField(verbose_name='Is active grant')),
                ('cost_per_day', models.IntegerField(verbose_name='Cost this grant per day')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'db_table': 'billing"."granted_access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrantedFilms',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(db_column='uuid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(verbose_name='User id')),
                ('movie_uuid', models.UUIDField(verbose_name='Movie id')),
                ('granted_at', models.DateTimeField(verbose_name='Granted at (same as parent grant)')),
                ('grant_uuid', models.UUIDField(verbose_name='Grant id')),
                ('is_active', models.BooleanField(verbose_name='Is active grant for film (same as parent grant')),
            ],
            options={
                'verbose_name': 'Grant filmworks',
                'verbose_name_plural': 'Grants filmworks',
                'db_table': 'billing"."granted_films',
                'managed': False,
            },
        ),
    ]
