version: '3'
services:
  db-billing:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data-billing:/var/lib/postgresql/data
    env_file:
      - admin-panel/.env.example
    ports:
      - '5432:5432'

  admin-panel:
    container_name: admin-panel
    build: ./admin-panel/
    command: /opt/app/run_uwsgi.sh
    env_file:
      - admin-panel/src/config/.env
    volumes:
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    depends_on:
      - db-billing

  access-api:
    container_name: access-api
    build: ./access-api/
    env_file:
      - access-api/.env
    depends_on:
      - db-billing

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx-admin/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-admin/configs:/etc/nginx/conf.d:ro
      - static_volume:/var/www/static/
      - media_volume:/var/www/media/
    depends_on:
      - admin-panel
      - access-api
    ports:
      - "8000:80"

  redis:
    container_name: redis
    image: redis:6.0.9
    restart: on-failure
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.12-rc-management
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    depends_on:
      - admin-panel
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    container_name: celery
    build: ./admin-panel/
    command: celery --app=config worker --loglevel=info
    env_file:
      - ./admin-panel/src/config/.env
    depends_on:
      - rabbitmq

  celery-beat:
    container_name: celery-beat
    build: ./admin-panel/
    command: celery --app=config beat --loglevel=info
    env_file:
      - ./admin-panel/src/config/.env
    depends_on:
      - rabbitmq

  flower:
    container_name: flower
    build: ./admin-panel/
    command: celery --app=config flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./admin-panel/src/config/.env
    depends_on:
      - celery
      - rabbitmq
      - admin-panel

volumes:
  postgres_data-billing:
  static_volume:
  media_volume: