# Generated by Django 3.2 on 2023-05-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_payment_gw_product_id'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='subscriptions',
            field=models.ManyToManyField(related_name='films', through='billing.SubscriptionFilmwork', to='billing.Subscription'),
        ),
    ]
