# Generated by Django 3.2 on 2023-05-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_films'),
        ('movies', '0002_filmwork_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='subscriptions',
            field=models.ManyToManyField(related_name='films_relations', through='billing.SubscriptionFilmwork', to='billing.Subscription'),
        ),
    ]
