"""subscription,filmworks ro added

Revision ID: 6f4c16f46e85
Revises: a8248ebe1836
Create Date: 2023-05-24 15:30:17.813478

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f4c16f46e85'
down_revision = 'a8248ebe1836'
branch_labels = None
depends_on = 'a8248ebe1836'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
op.drop_table('django_content_type')
    op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_table('django_migrations')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    op.drop_table('django_session')
    op.drop_table('person')
    op.drop_index('person_film_work_film_work_id_1724c536', table_name='person_film_work')
    op.drop_index('person_film_work_person_id_196d24de', table_name='person_film_work')
    op.drop_table('person_film_work')
    op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index('genre_film_work_film_work_id_65abe300', table_name='genre_film_work')
    op.drop_index('genre_film_work_genre_id_88fbcf0d', table_name='genre_film_work')
    op.drop_table('genre_film_work')
    op.drop_table('genre')
    op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.alter_column('film_work', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('film_work', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('film_work_creation_date_idx', table_name='film_work')
    op.alter_column('subscription_filmwork', 'filmwork_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subscription_filmwork', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('subscription_filmwork_filmwork_id_ae3a7a83', table_name='subscription_filmwork')
    op.drop_index('subscription_filmwork_idx', table_name='subscription_filmwork')
    op.drop_index('subscription_filmwork_subscription_id_2223a847', table_name='subscription_filmwork')
    op.drop_constraint('subscription_filmwork_filmwork_id_ae3a7a83_fk_film_work_id', 'subscription_filmwork', type_='foreignkey')
    op.drop_constraint('subscription_filmwork_subscription_id_2223a847_fk_subscribe_id', 'subscription_filmwork', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_filmwork', 'film_work', ['filmwork_id'], ['id'], source_schema='content', referent_schema='content')
    op.create_foreign_key(None, 'subscription_filmwork', 'subscribe', ['subscription_id'], ['id'], source_schema='content', referent_schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_filmwork', schema='content', type_='foreignkey')
    op.drop_constraint(None, 'subscription_filmwork', schema='content', type_='foreignkey')
    op.create_foreign_key('subscription_filmwork_subscription_id_2223a847_fk_subscribe_id', 'subscription_filmwork', 'subscribe', ['subscription_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('subscription_filmwork_filmwork_id_ae3a7a83_fk_film_work_id', 'subscription_filmwork', 'film_work', ['filmwork_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('subscription_filmwork_subscription_id_2223a847', 'subscription_filmwork', ['subscription_id'], unique=False)
    op.create_index('subscription_filmwork_idx', 'subscription_filmwork', ['subscription_id', 'filmwork_id'], unique=False)
    op.create_index('subscription_filmwork_filmwork_id_ae3a7a83', 'subscription_filmwork', ['filmwork_id'], unique=False)
    op.alter_column('subscription_filmwork', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subscription_filmwork', 'filmwork_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('film_work_creation_date_idx', 'film_work', ['creation_date'], unique=False)
    op.alter_column('film_work', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('film_work', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_permission_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('genre',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='genre_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('genre_film_work',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('film_work_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['film_work_id'], ['film_work.id'], name='genre_film_work_film_work_id_65abe300_fk_film_work_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='genre_film_work_genre_id_88fbcf0d_fk_genre_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='genre_film_work_pkey'),
    sa.UniqueConstraint('genre_id', 'film_work_id', name='genre_film_work_idx')
    )
    op.create_index('genre_film_work_genre_id_88fbcf0d', 'genre_film_work', ['genre_id'], unique=False)
    op.create_index('genre_film_work_film_work_id_65abe300', 'genre_film_work', ['film_work_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('person_film_work',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('film_work_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['film_work_id'], ['film_work.id'], name='person_film_work_film_work_id_1724c536_fk_film_work_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='person_film_work_person_id_196d24de_fk_person_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='person_film_work_pkey'),
    sa.UniqueConstraint('film_work_id', 'person_id', 'role', name='film_work_person_idx')
    )
    op.create_index('person_film_work_person_id_196d24de', 'person_film_work', ['person_id'], unique=False)
    op.create_index('person_film_work_film_work_id_1724c536', 'person_film_work', ['film_work_id'], unique=False)
    op.create_table('person',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key')
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq')
    )
    op.drop_index(op.f('ix_billing_granted_films_uuid'), table_name='granted_films', schema='billing')
    op.drop_index(op.f('ix_billing_granted_films_movie_uuid'), table_name='granted_films', schema='billing')
    op.drop_table('granted_films', schema='billing')
    op.drop_index(op.f('ix_billing_granted_access_uuid'), table_name='granted_access', schema='billing')
    op.drop_index(op.f('ix_billing_granted_access_user_uuid'), table_name='granted_access', schema='billing')
    op.drop_table('granted_access', schema='billing')
    op.drop_index(op.f('ix_billing_transaction_uuid'), table_name='transaction', schema='billing')
    op.drop_index(op.f('ix_billing_transaction_user_uuid'), table_name='transaction', schema='billing')
    op.drop_index(op.f('ix_billing_transaction_type'), table_name='transaction', schema='billing')
    op.drop_table('transaction', schema='billing')
    op.drop_index(op.f('ix_billing_trans_order_uuid'), table_name='trans_order', schema='billing')
    op.drop_index(op.f('ix_billing_trans_order_user_uuid'), table_name='trans_order', schema='billing')
    op.drop_index(op.f('ix_billing_trans_order_subscribe_id'), table_name='trans_order', schema='billing')
    op.drop_index(op.f('ix_billing_trans_order_payment_session_id'), table_name='trans_order', schema='billing')
    op.drop_table('trans_order', schema='billing')
    op.drop_index(op.f('ix_billing_funds_hold_uuid'), table_name='funds_hold', schema='billing')
    op.drop_index(op.f('ix_billing_funds_hold_user_uuid'), table_name='funds_hold', schema='billing')
    op.drop_index(op.f('ix_billing_funds_hold_type'), table_name='funds_hold', schema='billing')
    op.drop_table('funds_hold', schema='billing')
    op.drop_index(op.f('ix_billing_balance_uuid'), table_name='balance', schema='billing')
    op.drop_index(op.f('ix_billing_balance_user_uuid'), table_name='balance', schema='billing')
    op.drop_table('balance', schema='billing')
    # ### end Alembic commands ###
